### ISSUE TITLE
Not working on Windows using Chrome

### ISSUE THREAD

**Issue by dnovicki** [t-mullen/video-stream-merger#21] opened 2018-08-22 23:31 UTC
I can hotswap streams and it reflects the newly added stream locally but the receiving client still gets the old stream. Any ideas?

**Comment by t-mullen** [comment] 2018-08-23 00:14
I'm assuming you're using an RTCPeerConnection to send the stream. Are you sure you're adding `merger.result` to the peer?

Any code sample you can provide would help.

**Comment by t-mullen** [comment] 2018-08-23 00:19
Also, does the P2P demo work for you? https://rationalcoding.github.io/video-stream-merger/demo/p2p.html

**Comment by t-mullen** [comment] 2018-09-11 05:37
Closing since I can't reproduce this.

**Closed as completed by t-mullen** 2018-09-11 05:37 UTC
Labels: need-more-info
